@startuml
Abstract Figure{
+ double area()
+ double perimeter()
+ boolean belongs(Point p)
}

Class Rectangle{
- Point topLeft
- Point bottomRight
+ Rectangle(Point topLeft, Point bottomRight)
+ double base()
+ double height()
+ double area()
+ double perimeter()
+ String toString()
}

Class Triangle{
- Point p1
- Point p2
- Point p3
+ Triangle(Point p1, Point p2, Point p3)
+ double area()
+ double perimeter()
- double firstSize()
- double secondSize()
- double thirdSize()
+ String toString()
}

Rectangle --|> Figure
Triangle --|> Figure

Class Ellipse{
# Point centerPoint
# int mayAxis
# int minAxis
+ Ellipse(Point center, int may, int min)
+ double area()
+ double perimeter()
+ String toString()
}

Class Circle{
+ Circle(Point center, int radius)
+ String toString()
}

Ellipse--|>Figure
Circle--|>Ellipse

@enduml