@startuml
class ComplexNumber{
- int real
- int imag
+ ComplexNumber(int real, int imag)
+ ComplexNumber(int real)
+ int GetReal()
+ int GetImag()
+ ComplexNumber addNumber(ComplexNumber num)
}
@enduml